#!/bin/sh

echo "
------------------------
 SHELL RSS TORRENT v1.7
   Script by Rafostar
------------------------
"

INDENT1="  "
INDENT2="     "
UPPER="ABCDEFGHIJKLMNOPQRSTUVWXYZ/ĄĆĘŁŃÓŚŹŻ"
LOWER="abcdefghijklmnopqrstuvwxyz/ąćęłńóśźż"
UA="Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/72.0"

parse_config() {
    WatchDir=$(xmllint_from_config "string(//config/watchdir[1]/text())")
    if [ -z "$WatchDir" ]
    then
        echo "Error: no <watchdir> in XML file"
    else
        echo "Torrents will be downloaded to: $WatchDir"

        HistoryPath=$(xmllint_from_config "string(//config/history[1]/text())")
        if [ ! -z "$HistoryPath" ]
        then
            echo "Using download history file: $HistoryPath"

            if [ -f "$HistoryPath" ]
            then
                HistoryData=$(cat "$HistoryPath")
            fi
        fi

        FeedsCount=$(xmllint_from_config "count(//config/feed)")
        echo "Total feeds in config: $FeedsCount"
        echo ""

        feed=1
        while [ $feed -le $FeedsCount ]
        do
            FeedUrl=$(xmllint_from_config "string(//config/feed[$feed]/url[1]/text())")

            if [ -z "$FeedUrl" ]
            then
                echo "Error: feed $feed has no URL"
            else
                FeedData=$(wget -U "$UA" -O - "$FeedUrl" 2> /dev/null)

                if [ -z "$FeedData" ]
                then
                    FeedData=$(wget -O - "$FeedUrl" 2> /dev/null)
                fi

                if [ -z "$FeedData" ]
                then
                    echo "Error: feed $feed has no data"
                else
                    echo "feed $feed: $FeedUrl"

                    for QueryFn in "contains" "starts-with"
                    do
                        find_in_feed $feed
                    done
                fi
            fi

            feed=$(( feed + 1 ))
        done
    fi
}

check_attributes() {
    QueryText=$(xmllint_from_config "string($QueryPath[$query]/text())")
    IgnoreCase=$(xmllint_from_config "count($QueryPath[$query][@ignore-case='1'])")

    if [ "$IgnoreCase" -eq 1 ]
    then
        ParsedQuery=$(xmllint_from_config "translate($QueryPath[$query]/text(), '$UPPER', '$LOWER')")
        Matches="//item[title[$QueryFn(translate(., '$UPPER', '$LOWER'), '$ParsedQuery')]]"
        TorrentCount=$(xmllint_from_feed "count($Matches/link)")
    else
        Matches="//item[title[$QueryFn(., '$QueryText')]]"
        TorrentCount=$(xmllint_from_feed "count($Matches/link)")
    fi
}

find_in_feed() {
    QueryPath="//config/feed[$1]/$QueryFn"
    QueryCount=$(xmllint_from_config "count($QueryPath)")

    if [ "$QueryCount" -ge 1 ]
    then
        query=1
        while [ $query -le $QueryCount ]
        do
            check_attributes $1

            if [ ! -z "$TorrentCount" ]
            then
                echo "$INDENT1 $QueryFn $query: $QueryText, found: $TorrentCount"

                torrent=1
                while [ $torrent -le $TorrentCount ]
                do
                    TorrentLink=$(find_torrent_attr "enclosure")
                    if [ -z "$TorrentLink" ]
                    then
                        TorrentLink=$(xmllint_from_feed "string($Matches[$torrent]/link/text())")
                    fi

                    if [ ! -z "$TorrentLink" ]
                    then
                        if [ ! -z "$HistoryData" ]
                        then
                            case "$HistoryData" in
                                *"$TorrentLink"*) echo "$INDENT2 torrent $torrent in download history" ;;
                                *) download_torrent "$TorrentLink" ;;
                            esac
                        else
                            download_torrent "$TorrentLink"
                        fi
                    else
                        echo "$INDENT2 torrent $torrent without a link"
                    fi

                    torrent=$(( torrent + 1 ))
                done
            fi

            query=$(( query + 1 ))
        done
    fi
}

find_torrent_attr() {
    ATTR=$(xmllint_from_feed "count($Matches[$torrent]/$1)")
    if [ "$ATTR" -eq 1 ]
    then
        ATTR_TORRENT=$(xmllint_from_feed "count($Matches[$torrent]/$1[@type='application/x-bittorrent'])")
        if [ "$ATTR_TORRENT" -eq 1 ]
        then
            ATTR_URL=$(xmllint_from_feed "string($Matches[$torrent]/$1/@url)")
            if [ ! -z "$ATTR_URL" ]
            then
                echo "$ATTR_URL"
            fi
        fi
    fi
}

xmllint_from_config() {
    RESULT=$(xmllint --xpath "$1" "$ConfigPath" 2> /dev/null)
    echo "$RESULT"
}

xmllint_from_feed() {
    RESULT=$(echo "$FeedData" | xmllint --format --xpath "$1" - 2> /dev/null)
    echo "$RESULT"
}

write_to_history() {
    if [ ! -z "$HistoryPath" ]
    then
        echo "$1" >> "$HistoryPath"
    fi

    HistoryData=$(echo -e "$HistoryData\n$1")
}

download_torrent() {
    echo "$INDENT2 torrent $torrent: $1"

    wget -q --content-disposition -U "$UA" -P "$WatchDir" "$1" 2> /dev/null
    if [ $? -ne 0 ]
    then
        wget -P "$WatchDir" "$1" > /dev/null 2> /dev/null
        if [ $? -eq 0 ]
        then
            write_to_history "$1"
        fi
    else
        write_to_history "$1"
    fi
}

ConfigPath=$1
if [ -z "$ConfigPath" ]
then
    ME=$(basename "$0")
    echo "Usage: $ME <config_path>"
else
    if [ -f "$ConfigPath" ]
    then
        XmlInstalled=$(xmllint --version > /dev/null 2> /dev/null)
        if [ $? -eq 0 ]
        then
            parse_config
        else
            echo "Error: xmllint is not installed"
        fi
    else
        echo "Error: file $ConfigPath does not exist"
    fi
fi
